#!/usr/bin/env python3

import mafia

class FakeRole(mafia.Role):
  @property
  def action(self):
    return "FAKE"

print("| Role | Action | Description |")
print("| ---- | ------ | ----------- |")
for role in mafia.ROLES:
  exemplar = role(FakeRole(mafia.Town()))
  action = exemplar.action if exemplar.action != "FAKE" else ""
  if action: action = action.__class__.__name__
  print("| **%s** | *%s* | %s |" % (role.name(), action, role.description))
