#!/bin/sh

cd "`dirname "$0"`"/..

nosetests || exit 1

echo
! grep -r "print(" mafia/*.py mafia/*/*.py \
  --exclude=mafia/util.py \
  --exclude=mafia/test/readme_test.py \
  --exclude=mafia/test/test_game.py \
  || { echo "\nFAIL: Remove leftover print statements before committing."; exit 1; }

echo
! grep -r "debug=True" mafia/*.py mafia/*/*.py \
  --exclude=mafia/util.py \
  || { echo "\nFAIL: Remove leftover 'debug=True's before committing."; exit 1; }

GREEN=`tput setaf 2`
RESET=`tput sgr0`
echo "Presubmits ${GREEN}PASSED${RESET}.\n"
